apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: '{{ include "hnc.fullname" . }}-view'
rules:
  - apiGroups:
      - hnc.x-k8s.io
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
