apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: '{{ include "hnc.fullname" . }}-edit'
rules:
  - apiGroups:
      - hnc.x-k8s.io
    resources:
      - hierarchicalresourcequotas
      - subnamespaceanchors
    verbs:
      - '*'
